name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Install Dependencies (Frontend)
        working-directory: client
        run: npm install

      - name: Build Frontend
        working-directory: client
        run: npm run build

      - name: Install Dependencies (Backend)
        working-directory: backend
        run: npm install

      - name: Run Tests (Backend)
        working-directory: backend
        run: npm test

      
